-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- This file is automatically loaded by lazyvim.config.init
-- local Util = require("lazyvim.util")
--
-- -- DO NOT USE THIS IN YOU OWN CONFIG!!
-- -- use `vim.keymap.set` instead
-- local map = Util.safe_keymap_set
--
-- map("n", "<leader><leader>bu", ":tab DBUI<cr>", { desc = "Open Database client" })
--
-- map(
--   "n",
--   "<leader><leader>rr",
--   "<cmd>lua require('rest-nvim').run()<CR>",
--   { noremap = true, silent = true, description = "RestNvim: Run" }
-- )
